[project]
name = "gonzalez-sebastian-eliza-submission"
version = "0.1.0"
description = "RAG system to answer business questions by referencing SEC Annual and Quarterly Reports."
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi[standard]>=0.136.1",
    "langchain-chroma>=0.1.2",
    "langchain-ollama>=1.1.0",
]